AStar: gameBoard.cpp move.cpp
	g++ -fpermissive -std=c++11 -o AStar gameBoard.cpp move.cpp
debug:
	g++ -g -fpermissive -std=c++11 -o AStar gameBoard.cpp move.cpp
run: AStar
	./AStar

clean:
	rm AStar
